- name: generate modules var
  block:
    - name: Generate modules config
      set_fact:
        filebeat_modules: >
          {{
            (filebeat_modules | default([]))
            + [dict(
                item
            )]
          }}
      loop: 
        - "{{ all_filebeat_modules | default() }}"
        - "{{ host_filebeat_modules | default() }}"
        - "{{ group_filebeat_modules | default() }}"
      loop_control:
        label: 
          - "{{ item.module }}"
  run_once: true

- name: generate inputs var
  block:
    - name: Generate inputs config
      set_fact:
        filebeat_inputs: >
          {{
            (filebeat_inputs | default([]))
            + [dict(
                item
            )]
          }}
      loop:
        - "{{ all_filebeat_inputs | default() }}"
        - "{{ host_filebeat_inputs | default() }}"
        - "{{ group_filebeat_inputs | default() }}"
      loop_control:
        label: 
          - "{{ item.type }}"
  run_once: true
