- name: YUM || Install public signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
- name: YUM || Create repository file
  ansible.builtin.yum_repository:
    name: elastic-{{ major_version }}.x
    baseurl: https://artifacts.elastic.co/packages/{{ major_version }}.x/yum
    gpgcheck: true
    description: Elastic repository for {{ major_version }}.x packages
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: true
- name: YUM || Install filebeat
  ansible.builtin.yum:
    name: filebeat-{{ major_version }}.{{ minor_version }}.{{ patch_version }}
    update_cache: true
    state: present
  